# Generated by Django 3.1.3 on 2020-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=500)),
                ('phone', models.IntegerField(default=0)),
                ('no_of_patients', models.IntegerField(default=0)),
                ('no_of_recovered_patients', models.IntegerField(default=0)),
                ('no_of_decreased_patients', models.IntegerField(default=0)),
                ('no_of_patients_on_ventilator', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.TextField(max_length=1000)),
                ('address', models.TextField(max_length=1000)),
                ('email_id', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('room_no', models.IntegerField(default=0)),
                ('floor_no', models.IntegerField(default=0)),
                ('o2_level', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=97)),
                ('doctorId', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField(default=0)),
                ('patient_name', models.CharField(default='', max_length=500)),
                ('asymptomatic', models.BooleanField(default=False)),
                ('cough', models.BooleanField(default=False)),
                ('fever', models.BooleanField(default=False)),
                ('apetite_loss', models.BooleanField(default=False)),
                ('covid_test_result_3', models.BooleanField(default=True)),
                ('covid_test_result_2', models.BooleanField(default=True)),
                ('covid_test_result_1', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_no', models.IntegerField(default=0)),
                ('room_no', models.IntegerField(default=0)),
                ('ventilator', models.BooleanField(default=False)),
                ('occupied', models.BooleanField(default=False)),
                ('patient_id', models.IntegerField(default=0)),
            ],
        ),
    ]
