# Generated by Django 3.1.3 on 2020-12-29 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201226_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='apetite_loss',
            new_name='Covid_test',
        ),
        migrations.RemoveField(
            model_name='result',
            name='asymptomatic',
        ),
        migrations.RemoveField(
            model_name='result',
            name='cough',
        ),
        migrations.RemoveField(
            model_name='result',
            name='covid_test_result_1',
        ),
        migrations.RemoveField(
            model_name='result',
            name='covid_test_result_2',
        ),
        migrations.RemoveField(
            model_name='result',
            name='covid_test_result_3',
        ),
        migrations.RemoveField(
            model_name='result',
            name='fever',
        ),
        migrations.RemoveField(
            model_name='result',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='patient_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='health_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.result'),
        ),
    ]
