# Generated by Django 3.1.3 on 2020-12-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201229_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctorId',
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
    ]
