# Generated by Django 3.1.3 on 2020-12-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201229_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='floor_no',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='room_no',
        ),
        migrations.AddField(
            model_name='patient',
            name='room_no_and_bed_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
        ),
    ]
