# Generated by Django 3.1.3 on 2020-12-29 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201229_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='patient_id',
        ),
    ]
