# Generated by Django 3.1.3 on 2020-12-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_room_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
