# Generated by Django 3.1.3 on 2020-12-29 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_doctor_occupied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='no_of_decreased_patients',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='no_of_patients',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='no_of_patients_on_ventilator',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='no_of_recovered_patients',
        ),
    ]
