# Generated by Django 3.1.3 on 2020-12-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201229_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='experience',
            new_name='experience_in_years',
        ),
    ]
