# Generated by Django 3.1.3 on 2020-12-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201229_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.TextField(max_length=10),
        ),
    ]
