# Generated by Django 3.1.3 on 2020-12-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20201229_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='o2_level',
            new_name='oxygen_level',
        ),
    ]
