# Generated by Django 3.1.3 on 2020-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20201229_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='oxygen_level',
            field=models.IntegerField(default=90),
        ),
    ]
