# Generated by Django 3.1.3 on 2020-12-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201229_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.CharField(default='', max_length=500),
        ),
    ]
