# Generated by Django 3.1.3 on 2020-12-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20201231_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsTotalCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventilator', models.IntegerField(default=0)),
                ('ppe_kits', models.IntegerField(default=0)),
                ('gloves', models.IntegerField(default=0)),
                ('cotton_in_kg', models.IntegerField(default=0)),
            ],
        ),
    ]
