# Generated by Django 3.1.3 on 2021-01-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_patient_recovered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemstotalcount',
            name='cotton_in_kg',
        ),
    ]
