# Generated by Django 3.1.3 on 2021-01-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210126_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstotalcount',
            name='ppe_kits_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itemstotalcount',
            name='vaccines_used',
            field=models.IntegerField(default=0),
        ),
    ]
