# Generated by Django 3.1.3 on 2021-01-27 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210127_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='room_no_and_bed_no',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.room'),
        ),
    ]
